SAM_VERSION: 'vit_h'
SAM_CKPT_PATH: 'sam_ckpts/sam_vit_h_4b8939.pth'
PATCH_SIZE: 256
BATCH_SIZE: 4
DATA_WORKER_NUM: 1
TRAIN_EPOCHS: 10
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
ENABLE_POINT_JITTER: True
POINT_JITTER_STD: 1.0
ENABLE_POINT_DROP: False
POINT_DROP_PROB: 0.0
ENABLE_POINT_FP: False
POINT_FP_NUM: 0
POINT_FP_MIN_DIST: 16.0
ENABLE_ORIENTATION_HEAD: False
ENABLE_ORIENTATION_FUSION: False
ORIENTATION_DIM: 2
TOPO_ORIENTATION_ALPHA: 0.8

# Inference
INFER_BATCH_SIZE: 64
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16
ENABLE_BORDER_WEIGHT_FUSION: False
BORDER_WEIGHT_EPS: 1.0
EDGE_WEIGHT_MODE: 'min_margin'

# [0, 255]
ITSC_THRESHOLD: 128
ROAD_THRESHOLD: 128
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16
